_type: export
__export_format: 4
__export_date: 2022-04-13T09:36:31.189Z
__export_source: insomnia.desktop.app:v2022.2.1
resources:
  - _id: req_af94b1fd0fee4f6c875c3407bf216e75
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649842526228
    created: 1647468697590
    url: "{{ _.base_url }}/users/42"
    name: update
    description: ""
    method: PATCH
    body:
      mimeType: application/json
      text: |-
        {
        	"current_password": "admin1234567",
        	"password": "123456789"
        	
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_68616c3962d64f59808fc104fe8ea856
    authentication: {}
    metaSortKey: -1623031206109
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    parentId: wrk_7f7ec5c0670d47159b23ef3639718156
    modified: 1647887877531
    created: 1623040747451
    name: BankUsers
    description: ""
    environment: {}
    environmentPropertyOrder: {}
    metaSortKey: -1623031184767
    _type: request_group
  - _id: wrk_7f7ec5c0670d47159b23ef3639718156
    parentId: null
    modified: 1649716519870
    created: 1623031087994
    name: My Banking app
    description: ""
    scope: collection
    _type: workspace
  - _id: req_0561c6cf1691432188e424f2da74c906
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649842526576
    created: 1647534786576
    url: "{{ _.base_url }}/users/2/balance/add"
    name: Balance add
    description: ""
    method: PATCH
    body:
      mimeType: application/json
      text: |-
        {
        	"amount": "40"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_a8c65d1e7b114cddaba5f8cc1db41737
    authentication: {}
    metaSortKey: -1623031206096.5
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_8e84005f8a4b45b297e9e94f7e04f478
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649842526861
    created: 1649726718889
    url: "{{ _.base_url }}/users/2/balance/minus"
    name: Balance subtract
    description: ""
    method: PATCH
    body:
      mimeType: application/json
      text: |-
        {
        	"amount": "40"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_a8c65d1e7b114cddaba5f8cc1db41737
    authentication: {}
    metaSortKey: -1623031206090.25
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_35f84f8375504072a647861697304763
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649714983759
    created: 1647534368078
    url: "{{ _.base_url }}/users/2/balance"
    name: balance
    description: ""
    method: GET
    body:
      mimeType: application/json
      text: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_1a90b90ab70c4915be0c56b580433753
    authentication: {}
    metaSortKey: -1623031206084
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_fdbd69ee4c4542e3827d5923bf0e4410
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1647887754034
    created: 1623040747453
    url: "{{ _.base_url }}/users"
    name: index
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1623031206059
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_4ab04d3fa6664af99c03bc4eefc118bc
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649714978270
    created: 1623040747455
    url: "{{ _.base_url }}/users/2"
    name: show
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1623031206046.5
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_d7adcca532c747eabf366b62fe35ca07
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649841897654
    created: 1623040747458
    url: "{{ _.base_url }}/users"
    name: create
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |
        {
        	"username": "man123411",
        	"password": "admin1234567",
        	"email": "man731@yahoo.com"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_8c2d00d772ed4fb5ab3160aae2a85bbf
        disabled: false
    authentication: {}
    metaSortKey: -1623031206034
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_e3972c29de8645d1b4e99a60cc58b334
    parentId: fld_a326a0cbb48f427ea0da0ecb18da4bd0
    modified: 1649712531663
    created: 1623040747461
    url: "{{ _.base_url }}/users/1"
    name: delete
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1623031205984
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_eea4593126d94a8ca8f8ad317e7784d1ebe11e7f
    parentId: wrk_7f7ec5c0670d47159b23ef3639718156
    modified: 1623031088027
    created: 1623031088027
    name: Base Environment
    data: {}
    dataPropertyOrder: null
    color: null
    isPrivate: false
    metaSortKey: 1623031088027
    _type: environment
  - _id: jar_eea4593126d94a8ca8f8ad317e7784d1ebe11e7f
    parentId: wrk_7f7ec5c0670d47159b23ef3639718156
    modified: 1623031088028
    created: 1623031088028
    name: Default Jar
    cookies: []
    _type: cookie_jar
  - _id: spc_a4468ad64623425ea293d5250bd809ff
    parentId: wrk_7f7ec5c0670d47159b23ef3639718156
    modified: 1623031087995
    created: 1623031087995
    fileName: Insomnia
    contents: ""
    contentType: yaml
    _type: api_spec
  - _id: env_2efb47cb05eb4c2591c111e409852102
    parentId: env_eea4593126d94a8ca8f8ad317e7784d1ebe11e7f
    modified: 1623031261421
    created: 1623031222957
    name: Twitter Environment
    data:
      base_url: http://localhost:5000
    dataPropertyOrder:
      "&":
        - base_url
    color: null
    isPrivate: false
    metaSortKey: 1623031222957
    _type: environment
